server:
  port: 8080

spring:
  profiles:
    active: local
  application:
    name: "order"
  datasource:
    url: ${DB_CONNECTION_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

feign:
  client:
    config:
      default:
        logger-level: FULL

service:
  product:
    base-url: http://product:8080

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    com.gilbert.msa: DEBUG