spring:
  profiles:
    active: local
  application:
    name: "order"
  datasource:
    url: ${DB_CONNECTION_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

server:
  port: 8080

inner-communication:
  method: feign # feign or grpc

# feign
feign:
  client:
    config:
      default:
        logger-level: FULL

# grpc
grpc:
  client:
    product:
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    com.gilbert.msa: DEBUG
